import fs from "fs";
import path from "path";

export type KeyMetadata = {
  key_id: string;
  alg: "Ed25519";
  status: "active" | "deprecated" | "revoked";
  public_key: string; // Base64
  created_at: string;
};

const KEYS_DIR = path.join(process.cwd(), "twin_plus", "keys");
const PUBLIC_KEY_PATH = path.join(KEYS_DIR, "public_ed25519.pem");

export class KeyRegistry {
  private static instance: KeyRegistry;
  private keys: KeyMetadata[] = [];

  private constructor() {
    this.refresh();
  }

  public static getInstance(): KeyRegistry {
    if (!KeyRegistry.instance) {
      KeyRegistry.instance = new KeyRegistry();
    }
    return KeyRegistry.instance;
  }

  public refresh(): void {
    const keys: KeyMetadata[] = [];

    // Check for persistent key on disk
    if (fs.existsSync(PUBLIC_KEY_PATH)) {
      const pem = fs.readFileSync(PUBLIC_KEY_PATH, "utf8");
      // Basic extraction of base64 from PEM
      const base64 = pem
        .replace(/-----BEGIN PUBLIC KEY-----/, "")
        .replace(/-----END PUBLIC KEY-----/, "")
        .replace(/\s/g, "");

      keys.push({
        key_id: "tvk_2026_01",
        alg: "Ed25519",
        status: "active",
        public_key: base64,
        created_at: "2026-03-13T00:00:00.000Z",
      });
    } else {
      // Fallback placeholder until keys are generated by sign_passport
      keys.push({
        key_id: "tvk_2026_01",
        alg: "Ed25519",
        status: "active",
        public_key: "PENDING_GENERATION",
        created_at: "2026-03-13T00:00:00.000Z",
      });
    }

    this.keys = keys;
  }

  public getActiveKey(): KeyMetadata {
    const active = this.keys.find((k) => k.status === "active");
    if (!active) throw new Error("No active signing key found");
    return active;
  }

  public getKey(keyId: string): KeyMetadata | undefined {
    return this.keys.find((k) => k.key_id === keyId);
  }

  public getAllPublicKeys(): KeyMetadata[] {
    return this.keys;
  }
}
